### PR TITLE
Release 1.3.0

### PR DESCRIPTION
**Pull request by carter2422**
Version 1.3.0 introduces the add-on updater module from @TheDuckCow!

### CODE REVIEW

**Comment by OscarLeif** [comment]
I'm confused the stable version right now is the  1.2.5 or is this one 1.3.0 ?

**Comment by carter2422** [comment]
@OscarLeif I just pushed out both versions. 1.3.0 is the current stable.

**Comment by OscarLeif** [comment]
@carter2422 Ok I Will update to 1.3.0 thank you

**Comment by carter2422** [comment]
@OscarLeif any 1.3.0+ versions can now be updated right within Blender! 1.3.0 introduces the add-on updater.

**Comment by OscarLeif** [comment]
Amazing it even shows if you want to install an old version I guess the old version right now will be this one.

**Comment by carter2422** [comment]
Indeed! The minimum version allowed to install via the updater is 1.3.0, so that people don't accidentally install prior to the updater and not be able to update :)

**Pull request merged**
