### PR TITLE
Speed up self-intersection search

### PR DESCRIPTION
**Pull request by cobryan05**
This speeds up the self-intersection search when laying a polystrip. It reduces the complexity from O(n^2) to essentially O(logn). This won't speed up small strips very much, but should have a significant effect on longer strips.

### CODE REVIEW

**Comment by patmo141** [comment]
Thanks cobryan05.  I can't wait to test and explore these changes.  I see the KDTree :-).  I'm currently deep in edge-patches this weekend so it's toward the bottom of my to-do list for now but I just wanted to acknowledged that we've seen it and appreciate it and will get to it as soon as possible!

**Comment by cobryan05** [comment]
No hurry. I notice there are a lot of branches (and master isn't even the highest versioned branch). Is there something besides master I should be basing off of?

**Comment by carter2422** [comment]
@cobryan05 thanks! If you could actually base this off of the release/1.1.0 branch that'd be great. We refactored the mass majority of the codebase to be much more structured.

**Comment by cobryan05** [comment]
Whoops, I'm not familiar with the 'pull request' workflow. Didn't realize I pushed another patch onto this pull request.

Sure I'll rebase off 1.1.0

**Pull request closed without merging**
