### PR TITLE
add fly mode event & keybind

### PR DESCRIPTION
**Pull request by fayriot**

### CODE REVIEW

**Comment by carter2422** [comment]
Thanks for the PR @fayriot! I'll take a look at it just soon as I can.

In the mean time, what's your use case for Fly Mode during reotpo? Easier navigation?

**Comment by fayriot** [comment]
@carter2422 yes, for easier navigation and more accurate zoom.

**Comment by carter2422** [comment]
@vxlcoder shall we adapt this for `release/2.0.0` once the key issues are resolved?

**Comment by vxlcoder** [comment]
Sorry that I'm just now getting to this, @fayriot and @carter2422!
The changes were only for RF 1.3.  Since that version is deprecated with the release of RF 2.0, I've made the appropriate changes the RF 2 to add view navigation (see commit 703a3cb).
Thanks for the PR!
Closing for now.

**Pull request closed without merging**
